### ISSUE TITLE
Value Editing

### ISSUE THREAD

**Issue by GeoffGr** [usc-isi-i2/Web-Karma#259]
I am having issues  editing values within Karma after data import. I am running the current Vagrant deployment, following the instructions here: https://github.com/usc-isi-i2/Web-Karma/wiki/Installation%3A-Virtual-Box.

When attempting to click the check button (in Chrome and Firefox) to change the value I receive the following error:
![image](https://cloud.githubusercontent.com/assets/4147638/15406451/9a7786ec-1dd4-11e6-8fd4-284bf74b462d.png)

Am I doing something wrong or misinterpreting this feature?

Thanks.

**Comment by dkapoor** [comment]
Sorry about that but this feature was broken. We have fixed it and have pushed it to the development branch.
To get the changes, run the following from you Web-Karma/vagrant folder:
```
vagrant destroy
cd ..
git checkout development
git pull
cd vagrant
vagrant up
```

**Comment by GeoffGr** [comment]
The development branch version seems to be working now. I did seem to need to:
```
vagrant ssh
cd Web-Karma
git checkout development
git pull
exit
vagrant halt
vagrant up
```

after `vagrant destroy`, but I may not have destroyed from the correct location. Thanks.

In general, is there a tagged version which is recommended?

**Comment by szeke** [comment]
Word of caution, if you edit the data and later load the data again, the edits are not replayed after you apply the model. We are tempted to remove this feature because of this problem.

Is this an important feature for you? How would you think it should work to save the edits in the model? What if you apply the model to a different dataset?
