### ISSUE TITLE
Error when trying to publish model

### ISSUE THREAD

**Issue by rhao** [usc-isi-i2/Web-Karma#277]
I was working on a model, and when I click Publish -> R2RML Model, it says "Error: null". I have multiple files open in the same karma tab, and I can publish the other models, but not the one I was actually working on. This one was the result of unfolding a sheet - is there a different process I need to use to publish the model? Here are the most recent logs showing the error: https://gist.github.com/rhao/ef0f7260f9c7be08b4321001b9730200

**Comment by dkapoor** [comment]
Rebecca, can you send me your karma home folder, the input file and the model at location `/Users/rebeccahao/Documents/Projects/LODStories/aac-alignment/karma/models-autosave/WSP1WS454-Unfold: NPGObjThesTerms2_Sheet1-auto-model.ttl` I can start with that and see if I can reproduce it. Thanks.

**Comment by rhao** [comment]
Just emailed you!

**Comment by rhao** [comment]
Update: rebuilt the same model, and the same error occurred so I can't save it.

**Comment by dkapoor** [comment]
Model file sent by Rebecca: [WSP1WS454-Unfold_ NPGObjThesTerms2_Sheet1-auto-model.ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/797567/WSP1WS454-Unfold_.NPGObjThesTerms2_Sheet1-auto-model.ttl.txt)

**Comment by dkapoor** [comment]
![screen shot 2017-02-23 at 12 06 17 pm](https://cloud.githubusercontent.com/assets/1852707/23276789/84ff3ed6-f9c0-11e6-868d-625db8391bd8.png)
We had a bug replaying history that we have since fixed. I tried this on the latest version of development branch and am able to Unfold ThesXrefType  with "Term", "Use Other Columns" selected, then apply your auto saved model to the unfolded worksheet, make changes to the model and then publish it.

It should all work now.
