### ISSUE TITLE
 output after publish data to rdf, is not as desired

### ISSUE THREAD

**Issue by rabiam04** [usc-isi-i2/Web-Karma#287]
Hi,
I attached my output screenshot. The output after publish data to rdf, is not as desired. I don't know why these  strings (digits and alphabets) are coming.
In my initial dataset, I had some empty cells, I just remove that columns. The number of these digits and alphabet are minimize but not removed.

Please guide.
![output](https://cloud.githubusercontent.com/assets/22327197/19030828/cf67495e-8969-11e6-9ffc-85deffc9e4bd.png)

**Comment by jinjin304616** [comment]
Hi, I'm new to Karma. I can't even open my RDF after published. Any idea how to open or download it?
![image](https://cloud.githubusercontent.com/assets/13896872/19040136/7193e5ac-89b5-11e6-94b9-2f8ad628e418.png)

**Comment by rabiam04** [comment]
Please check your directory, publish rdf file auto save here
 ..\karma-web\src\main\webapp\publish\RDF

**Comment by dkapoor** [comment]
@rabiam04: Your RDF looks like:
`x hostname "PDB Server"`
and so on..
When your classes do not have URIs defined, Karma inserts Blank nodes with automatically generated ids for for them. That is what you are seeing as "x"
If you change your model and create a uri for what represents as "x", you would see the actual URIs instead of these blank node ids. 
There is a section in the wiki on how to specify URIs that could be useful: https://github.com/usc-isi-i2/Web-Karma/wiki/Modeling-Data#uris-for-classes
