### ISSUE TITLE
Error applying model

### ISSUE THREAD

**Issue by bsnikhila** [usc-isi-i2/Web-Karma#310]
The model for [NPG Objects](https://github.com/american-art/npg/tree/master/NPGObjects) was created by someone else a while ago. I am now trying to apply the model for NPG Objects on my system and I am getting this error:
Error executing command ChangeInternalNodeLinksCommand from history

**Comment by dkapoor** [comment]
[NPGObjects2-model.ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/743214/NPGObjects2-model.ttl.txt)
The model was generated with a version of Karma that had a bug that when links were changed using "Manage Links", it did not insert the class uris. This has been fixed since. I manually added the URIs in the model and now the attached model should work.
