### ISSUE TITLE
Undo/delete commands deletes the worksheet

### ISSUE THREAD

**Issue by marijane** [usc-isi-i2/Web-Karma#331]
**Environment:**
OS X 10.11.6 (15G1421)
Google Chrome Version 57.0.2987.133 (64-bit)
Karma version 2.052

**Steps to Reproduce:**
1. Load a data file
2. Do some transforms
3. Add some semantic types
4. Check a box next to a command in the command history
5. Select "Delete" from the menu at the top of the command history

**Result:**
- Karma deletes the selected command from the command history.
- Karma deletes the _entire_ worksheet and throws a bunch of errors.  The errors usually consist of a series of "Description: <column name> does not exist, using empty values" errors, and the last error is "Description: Error executing command SetSemanticTypeCommand from history".

**Expected Result:**
- Karma should only delete the selected command from the history
- Karma should not delete the worksheet

**Comment by marijane** [comment]
I want to note that I have assumed that the "Delete" in the command history menu is intended to delete or undo commands.  I have watched a bunch of Karma videos, some of which mentioned an Undo command that does not seem to exist in the current version.

**Comment by KimQ0126** [comment]
> I want to note that I have assumed that the "Delete" in the command history menu is intended to delete or undo commands. I have watched a bunch of Karma videos, some of which mentioned an Undo command that does not seem to exist in the current version.

Hi Marijane, according to your steps, I have reproduced the errors. However, since you haven't clarified which command you checked and deleted, we cannot completely reproduce your issue. For your first problem in the first comment, I assumed that you may delete a pyTransform column which have been executed Set Semantic Type command, so that when you run a command which will delete this column will also delete the related Set Semantic Type commands. I have updated the error notification to explain this situation. Moreover, I assumed that your second problem in your first comment maybe caused by our unclear notification. In fact, we do not deleted the whole worksheet when you deleted one command. We have changed the worksheet update notification in the development branch. For your second comment, we do have Undo command in the version 2.2, but we just support Undo the last delete. Thanks.
