### ISSUE TITLE
Bug in Karma batch mode

### ISSUE THREAD

**Issue by binh-vu** [usc-isi-i2/Web-Karma#372]
Karma version: 2.053

I use Karma to generate jsonld for this dataset (https://github.com/american-art/npg/tree/master/NPGObjAltTitles), but the result is incorrect.

The result should have about 5 attributes, but it only generates 2 attributes. Trying to export JSON from KarmaWeb also yields incorrect result.

**Comment by dkapoor** [comment]
The issue is because of a bug in Karma that did not order commands correctly based on their dependent columns. That bug has been fixed since, but this model seems to predate that fix.
As you can see, when you load the model, the TitleURI comes empty and hence that class will not get generated.

![screen shot 2018-03-13 at 11 13 36 am](https://user-images.githubusercontent.com/1852707/37361307-d24b983e-26af-11e8-9cb8-762fa5fdf32e.png)

To fix the model, I had to change the TitleURI transform slightly and then revert back and publish the model.
The attached model would generate the correct json-ld

[NPGObjAltTitles2-model.ttl.txt](https://github.com/usc-isi-i2/Web-Karma/files/1808153/NPGObjAltTitles2-model.ttl.txt)

Thanks
