### ISSUE TITLE
List of PyTransform functions

### ISSUE THREAD

**Issue by ekontopoulos** [usc-isi-i2/Web-Karma#453]
What is the list of available functions one can use in PyTransform? The ones mentioned in the documentation are: getValue, getRowIndex, getValueFromNestedColumnByIndex, but I guess there are other ones as well (?)

**Comment by rutujarane** [comment]
The above are special functions provided so that you can access the data. You can use any Python functions for this. You can even design your own user-defined functions. While designing your own user-defined functions, you just need to be mindful of the memory limit on importing Python packages into Karma.
