### ISSUE TITLE
java.base does not opens.java.util to unnamed modüle @5da94a74

### ISSUE THREAD

**Issue by dilan9461** [usc-isi-i2/Web-Karma#515]
![IMG_20211221_233642](https://user-images.githubusercontent.com/82340714/146994384-bfdd4330-425e-48c8-8244-523d2124f7ed.jpg)

unable to make field private transient Java.util navigablemap Java.util. Treeset m accessible: modüle java.base does not opens.java.util to unnamed modüle @5da94a74 I am getting the above error. What should I do ?

**Comment by Bidisha010496** [comment]
Hi,

Sorry for the delayed response. A few question to resolve the issue ?

1. Are you getting this error with the latest version of the app ? 
2. Could you also provide the sequence of steps that gave you this error , so that I can reproduce it in my system ?
3. Which operating system are you running this on ?

**Comment by Bidisha010496** [comment]
Please re-open the issue if it still exists with the new release.
