### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by mtthsdzwn** [usc-isi-i2/Web-Karma#538]
I am trying to install from source on my macbook but `mvn clean install` fails

## Steps to reproduce the behavior:

1. `gh repo clone usc-isi-i2/Web-Karma`
2. `mvn clean install`

## Expected behavior
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
## Screenshots
<img width="1128" alt="Screenshot 2022-05-04 at 16 43 07" src="https://user-images.githubusercontent.com/1580106/166706154-6dd55d3b-3912-4a19-ad96-6430f0dae0d9.png">

## Desktop
macOS 12.3.1 (21E258)
```
java -version 
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
```
```
mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /usr/local/Cellar/maven/3.8.5/libexec
Java version: 18.0.1, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.3.1", arch: "x86_64", family: "mac"
```

**Comment by Bidisha010496** [comment]
Hi, I think the issue is happening because your maven configuration is using java version 18.0.1. It should be using java version 1.8. Please follow the steps in https://euedofia.medium.com/fix-default-java-version-on-maven-on-mac-os-x-156cf5930078 to update the java version for maven.
Once maven's java version is updated, the output of maven -version command should look like this : 
<img width="1238" alt="Screenshot 2022-09-05 at 6 03 16 PM" src="https://user-images.githubusercontent.com/17422330/188525930-d7e310ae-681f-49ab-b7c1-80600120dfe2.png">
 Feel free to reopen the issue, if it's still not resolved.
